version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - intercity-network

  datacollector:
    build: .
    container_name: datacollector
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo
    networks:
      - intercity-network

networks:
  intercity-network:
    driver: bridge

volumes:
  mongo-data:
